spring.application.name=estudos
spring.datasource.url=jdbc:postgresql://localhost:5432/estudo
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
#coloquei meus dados sensíveis no meu OS via git bash para evitar vaza-los.